# Cell 2 - train
from ultralytics import YOLO

model = YOLO("yolov8s.pt")

model.train(
    data="data.yaml",  
    epochs=100,
    imgsz=1024,
    batch=16,
    device=0,
    workers=4,
    cache=False,
    amp=True,
    rect=False,
    single_cls=True,
    optimizer="AdamW",
    lr0=0.001,
    lrf=0.1,
    momentum=0.937,
    weight_decay=5e-4,
    warmup_epochs=5,
    cos_lr=True,
    degrees=0.0,
    fliplr=0.5,
    flipud=0.5,
    hsv_h=0.015,
    hsv_s=0.5,
    hsv_v=0.4,
    scale=0.5,
    mosaic=0.5,
    close_mosaic=20,
    translate=0.1,
    erasing=0.3,
    box=7.5,
    cls=0.3,
    dfl=1.5,
    patience=50,
    save=True,
    save_period=10,
    verbose=True,
    project="yolo_runs",
    name="human",
)